# Generated by Django 4.2.6 on 2023-11-05 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200904_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dateissued',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='startdate',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('-----', '-----'), ('cyber', 'Cyber'), ('it', 'IT'), ('Creative and Design', 'Creative and Design'), ('Legal and Compliance', 'Legal and Compliance'), ('research', 'Research')], max_length=125),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(choices=[('-----', '-----'), ('cyber', 'Cyber'), ('it', 'IT'), ('Creative and Design', 'Creative and Design'), ('Legal and Compliance', 'Legal and Compliance'), ('research', 'Research')], default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(choices=[('-----', '-----'), ('employee', 'Employee'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('team leader', 'Team leader')], default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('-----', '-----'), ('employee', 'Employee'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('team leader', 'Team leader')], max_length=125),
        ),
    ]
